name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build and tag image
        run: |
          docker build -t tiarapuspa/uas-pccks:latest -f Dockerfile .

      - name: push to dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_ACCESSTOKEN}} && docker push tiarapuspa/uas-pccks:latest
