name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build and tag image
      run: |
        docker build -t tiarapuspa/uas-pccks:latest -f Dockerfile .
    
    - name: push to dockerhub
      run: docker login -u ${{secrets.tiarapuspa}} -p ${{secrets.tiarapuspaaziza}} && docker push tiarapuspa/uas-pccks:latest
